FROM centos:7
MAINTAINER Sadashiv Kulthe
RUN yum -y install httpd
# ADD and COPY are almost similar
ADD code /var/www/html
EXPOSE 80
#ENV <key>=<value>
#ENV DB_HOST=test
CMD ["apachectl" "-D" "FOREGROUND"]
#ENTRYPOINT don't allow to change it run-time. Run at entry and as fixed string
#ENTRYPOINT ["apachectl" "-D" "FOREGROUND"]