---
- hosts: localhost
  tasks: 
    - include_role:
        name: cloud
- hosts: webserver
  become: True
  gather_facts: True
  remote_user: ec2-user
  vars:
    ansible_ssh_private_key_file: /home/ec2-user/environment/my-key.pem
  tasks:
    - include_role:
        name: webstack
        