---
- name: example using security group rule descriptions
  ec2_group:
    name: "{{ sgname }}"
    description: my webserver sg
    vpc_id: "{{ vpcid }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        ports:
          - 80
          - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port 80 and 22 for ssh
  register: sg_out
- debug:
    var: sg_out